#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

CONFIG_DIR="./install.conf.d"
DOTBOT="${BASEDIR}/dotbot/bin/dotbot"

# Install dotbot and plugins
git submodule update --init --recursive

# Update PATH
export PATH+=:$HOME/.cargo/bin:$HOME/n/bin

# Make sure python3 is used
sudo ln -fs /usr/bin/python3 /usr/bin/python

# Install apt packages
sudo "${DOTBOT}" -d "${BASEDIR}" -c "${CONFIG_DIR}/aptget.yaml" -p "./plugins/aptget/aptget.py" "${@}"

# Install other packages
"${DOTBOT}" -d "${BASEDIR}" -c "${CONFIG_DIR}/packages.yaml" "${@}"

# Install rust packages
"${DOTBOT}" -d "${BASEDIR}" -c "${CONFIG_DIR}/rust.yaml" -p "./plugins/rust/rust.py"  "${@}"

# Setup links, packages config and nvim plugins
"${DOTBOT}" -d "${BASEDIR}" -c "${CONFIG_DIR}/main.yaml" "${@}"

./install.d/caps2esc
