#!/usr/bin/env bash

CONFIG_DIR="./install.conf.d"
MAIN_CONF="main.yaml"
APTGET_CONF="aptget.yaml"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/${MAIN_CONF}" "${@}"
sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/${APTGET_CONF}" -p "./plugins/aptget/aptget.py"
