---
- hosts: localhost
  become: false
  vars:
    global_packages:
      - git-delta
      - du-dust
      - viu
      - dua
      - ripgrep
      # Already installed with a tasks/bin script
      # - atuin
      # - eza
      # - bat
      # - broot
  tasks:
    - name: Download rustup script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: 'u+rwx'

    - name: Run rustup
      shell: /tmp/rustup.sh -y

    - name: Remove rustup.sh
      file:
        path: /tmp/rustup.sh
        state: absent

    - name: Download binstall installer
      get_url:
        url: https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh
        dest: /tmp/install-from-binstall-release.sh
        mode: 'u+rwx'

    - name: Run the install script
      shell: /tmp/install-from-binstall-release.sh

    - name: Remove the install-from-binstall-release.sh
      file:
        path: /tmp/install-from-binstall-release.sh
        state: absent

    - name: install global packages
      command: cargo binstall --no-confirm "{{ item }}"
      loop: '{{ global_packages }}'
