---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Bootstrap development environment
  hosts: localhost
  tasks:
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:phoerious/keepassxc
        state: present
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        name:
          - git
          - curl
          - zsh
          - unzip
          - zip
          - luarocks
          - btop
          - jq
          - bfs
        state: present

    - name: Install python3 tools
      ansible.builtin.pip:
        name:
          - yamllint
          - pynvim
        state: present
        extra_args: --break-system-packages

    - name: Change shell
      become: true
      ansible.builtin.user:
        name: dev
        shell: /bin/zsh

    - name: Install zgen
      ansible.builtin.git:
        repo: https://github.com/tarjoilija/zgen.git
        dest: ~/.zgen
