---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- hosts: localhost
  vars:
    dotfiles: "{{ (ansible_env.PWD, '..', 'dotfiles') | ansible.builtin.path_join | ansible.builtin.normpath }}"
  tasks:
    - name: Ensure directories exists
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - .config
        - .docker
        - .ssh
        - .local/bin

    - name: list home dotfiles
      ansible.builtin.find:
        paths: '{{ dotfiles }}/home/'
        file_type: any
        hidden: true
      register: home_dotfiles
    - name: link home dotfiles
      ansible.builtin.file:
        src: '{{ item.path }}'
        path: '{{ ansible_env.HOME }}/{{ item.path | basename }}'
        state: link
        force: true
      loop: '{{ home_dotfiles.files|flatten(levels=1) }}'
      loop_control:
        label: '{{ item.path }}'

    - name: list config dotfiles
      ansible.builtin.find:
        paths: '{{ dotfiles }}/config/'
        file_type: any
      register: config_dotfiles
    - name: link config dotfiles
      ansible.builtin.file:
        src: '{{ item.path }}'
        path: '{{ ansible_env.HOME }}/.config/{{ item.path | basename }}'
        state: link
      loop: '{{ config_dotfiles.files|flatten(levels=1) }}'
      loop_control:
        label: '{{ item.path }}'

    - name: list ssh dotfiles
      ansible.builtin.find:
        paths: '{{ dotfiles }}/ssh/'
        file_type: any
      register: ssh_dotfiles
    - name: link ssh dotfiles
      ansible.builtin.file:
        src: '{{ item.path }}'
        path: '{{ ansible_env.HOME}}/.ssh/{{ item.path | basename }}'
        state: link
      loop: '{{ ssh_dotfiles.files|flatten(levels=1) }}'
      loop_control:
        label: '{{ item.path }}'

    - name: list docker dotfiles
      ansible.builtin.find:
        paths: '{{ dotfiles }}/docker/'
        file_type: any
      register: docker_dotfiles
    - name: link docker dotfiles
      ansible.builtin.file:
        src: '{{ item.path }}'
        path: '{{ ansible_env.HOME}}/.docker/{{ item.path | basename }}'
        state: link
      loop: '{{ docker_dotfiles.files|flatten(levels=1) }}'
      loop_control:
        label: '{{ item.path }}'

    - name: list bin dotfiles
      ansible.builtin.find:
        paths: '{{ dotfiles }}/bin/'
        file_type: any
      register: bin_dotfiles
    - name: link bin dotfiles
      ansible.builtin.file:
        src: '{{ item.path }}'
        path: '{{ ansible_env.HOME}}/.local/bin/{{ item.path | basename }}'
        state: link
      loop: '{{ bin_dotfiles.files|flatten(levels=1) }}'
      loop_control:
        label: '{{ item.path }}'
