set nocompatible

" set shell
set shell=zsh

" set runtime path
set runtimepath+=~/.vim_config

source ~/.vim/plug.vim
source ~/.vim/config.vim
source ~/.vim/plugins_config.vim
source ~/.vim/filetypes.vim
source ~/.vim/abbr.vim

set exrc

