#!/bin/bash

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKDIR="$(mktemp -d -p "${DIR}")"

if [[ ! "$WORKDIR" || ! -d "$WORKDIR" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

function cleanup {
  rm -rf "${WORKDIR}"
}

trap cleanup EXIT

# Install deps
sudo apt update
sudo apt install -y libudev-dev libyaml-cpp-dev libevdev-dev cmake

# Install interception
cd "${WORKDIR}"
git clone https://gitlab.com/interception/linux/tools.git
cd tools
mkdir build
cd build
cmake ..
make
sudo make install

# Install caps2esc
cd "${WORKDIR}"
git clone https://gitlab.com/interception/linux/plugins/caps2esc.git
cd caps2esc
mkdir build
cd build
cmake ..
make
sudo make install

cd "${DIR}"

# Configure udevmon with caps2esc
sudo tee /etc/udevmon.yaml <<EOF
- JOB: "intercept -g \$DEVNODE | caps2esc | uinput -d \$DEVNODE"
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
EOF

sudo tee /etc/systemd/system/udevmon.service <<EOF
[Unit]
Description=udevmon
Wants=systemd-udev-settle.service
After=systemd-udev-settle.service

[Service]
ExecStart=/usr/bin/nice -n -20 /usr/local/bin/udevmon -c /etc/udevmon.yaml

[Install]
WantedBy=multi-user.target
EOF

# Enable udevmon
sudo systemctl enable --now udevmon
