#!/bin/bash

set -eu

REPO="docker/compose"
TARGET="/usr/local/bin/docker-compose"

curl -s "https://api.github.com/repos/${REPO}/releases/latest" \
| grep "browser_download_url.*docker-compose-$(uname -s)-$(uname -m)\"" \
| cut -d : -f 2,3 \
| tr -d \" \
| sudo xargs -n 1 curl -o "${TARGET}" -L

sudo chmod +x "${TARGET}"
