#!/bin/bash

set -eu

BIN_PATH=/usr/local/bin
BIN_NAME=nvim

get_latest_bin_url() {
  case "$(uname -s)" in
      Linux*)     PACKAGE=nvim.appimage;;
      *)          echo "Unsupported machine"; exit 1
  esac

  VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/neovim/neovim/releases/latest | jq -r .tag_name)
  PACKAGE="https://github.com/neovim/neovim/releases/download/${VERSION}/${PACKAGE}"
  echo ${PACKAGE}
}

bin_version() {
  nvim -v | head -1 | awk '{ print $2  }'
}

# Common part

CURRENT_VERSION=$(bin_version)

if [ -f "${BIN_PATH}/${BIN_NAME}" ]; then
  if [ -f "${BIN_PATH}/${BIN_NAME}-${CURRENT_VERSION}" ]; then
    sudo rm "${BIN_PATH}/${BIN_NAME}"
  else
      sudo mv "${BIN_PATH}/${BIN_NAME}" "${BIN_PATH}/${BIN_NAME}-${CURRENT_VERSION}"
  fi
fi


curl -L -o ${BIN_NAME} "$(get_latest_bin_url)"
chmod +x ${BIN_NAME}
sudo mv "${BIN_NAME}" "${BIN_PATH}/${BIN_NAME}"
