---
- hosts: localhost
  tasks:
    - name: Install regolith key
      ansible.builtin.get_url:
        url: https://regolith-desktop.org/regolith.key
        dest: /tmp/regolith.key

    - name: Dearmor key
      ansible.builtin.command: gpg --dearmor /tmp/regolith.key

    - name: Copy key
      become: true
      ansible.builtin.copy:
        src: /tmp/regolith.key.gpg
        dest: /usr/share/keyrings/regolith-archive-keyring.gpg

    - name: Remove tmp key files
      loop:
        - /tmp/regolith.key.gpg
        - /tmp/regolith.key
      ansible.builtin.file:
        state: absent
        path: '{{ item }}'

    - name: Add regolith repository
      become: true
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_2-ubuntu-noble-amd64 noble main'
        state: present
        update_cache: yes

    - name: Install regolith
      become: true
      ansible.builtin.package:
        name:
          - regolith-desktop
          - regolith-session-flashback
          - regolith-session-sway
          - regolith-look-gruvbox
        state: present
