---
- hosts: localhost
  become: false
  vars:
    instpath: '{{ ansible_env.HOME }}/.local/bin'
    org: BurntSushi
    repo: ripgrep
    binname: rg
    filename: "{{ 'ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz' if ansible_architecture == 'x86_64' else 'ripgrep-14.1.0-aarch64-unknown-linux-gnu.tar.gz' }}"
    dirname: "{{ 'ripgrep-14.1.0-x86_64-unknown-linux-musl' if ansible_architecture == 'x86_64' else 'ripgrep-14.1.0-aarch64-unknown-linux-gnu' }}"
    version: latest
    project_url: https://api.github.com/repos/{{ org }}/{{ repo }}/releases
  tasks:
    - name: check {{ repo }} version
      uri:
        url: '{{ project_url }}/{{ version }}'
        return_content: true
      register: latest_version

    - name: check if {{ repo }}-{{ version }} is already there
      stat:
        path: '{{ instpath }}/{{ repo }}-{{ latest_version.json.tag_name }}'
      register: newestbinary

    - name: download and link to version {{ version }}
      block:
        - name: 'check if {{ instpath }} exists'
          file:
            path: '{{ instpath }}'
            state: directory
            mode: '0755'

        - name: create tempdir
          tempfile:
            state: directory
            suffix: dwnld
          register: tempfolder_1

        - name: 'installing {{ repo }} {{ latest_version.json.tag_name }}'
          # idea from: https://stackoverflow.com/a/62672308/886659
          loop: '{{ latest_version.json.assets }}'
          loop_control:
            label: '{{ item.name }}'
          when:
            - 'filename|string == item.name'
          unarchive:
            remote_src: yes
            src: '{{ item.browser_download_url }}'
            dest: '{{ tempfolder_1.path }}'
            keep_newer: yes

        - name: command because no mv available
          command: mv "{{ tempfolder_1.path }}/{{ dirname }}" "{{ instpath }}/{{ binname }}-{{ latest_version.json.tag_name }}"
          args:
            creates: '{{ instpath }}/{{ binname }}-{{ latest_version.json.tag_name }}'

        - name: 'link {{ binname }}-{{ latest_version.json.tag_name }} -> {{ repo }} '
          file:
            src: '{{ instpath }}/{{ binname }}-{{ latest_version.json.tag_name }}'
            dest: '{{ instpath }}/{{ binname }}'
            state: link
            force: yes

      when: not newestbinary.stat.exists
      always:
        - name: delete {{ tempfolder_1.path|default("tempfolder") }}
          file:
            path: '{{ tempfolder_1.path }}'
            state: absent
          when: tempfolder_1.path is defined
          ignore_errors: true
# vim:ft=yaml.ansible:
