# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/developer/.zshrc'

autoload -Uz compinit
compinit
#End of lines added by compinstall

### Personal stuff

# Load personal configs
source ~/.dotfiles/zsh/combo.zsh
. ~/.dotfiles/zsh/prompt.zsh
. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/error.zsh
. ~/.dotfiles/zsh/functions.zsh
. ~/.dotfiles/git/git-aliases.zsh


# Set editor
if [[ -z "$EDITOR" ]]; then
    export EDITOR=vim
fi

#Locale
LANG="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"

#autoload -Uz add-zsh-hook
#add-zsh-hook precmd "dynPrompt $?"

# Add v command on normal mode to edit current line with $EDITOR
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# AutoSuggest 
[ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=7

# Autojump
[ -f /usr/share/autojump/autojump.sh ] && . /usr/share/autojump/autojump.sh

# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# N
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# If ag or pt is present adapt fzf default command, with a preference for pt
command -v ag >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git --ignore custom_plugins -g ""'
command -v pt >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND='pt --hidden -g=""'

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

