profile_zsh=false

if $profile_zsh; then
  zmodload zsh/zprof
fi

export HISTFILE=~/.histfile
export HISTSIZE=100000
export SAVEHIST=100000
export HISTCONTROL=ignoredups:erasedups
setopt appendhistory autocd beep notify
setopt HIST_IGNORE_DUPS HIST_IGNORE_ALL_DUPS
bindkey -v

if [ -n "${TMUX_PANE}" ]; then
  HISTS_DIR=$HOME/.zsh_history.d
  mkdir -p "${HISTS_DIR}"
  export HISTFILE="${HISTS_DIR}/histfile_tmux_$(tmux display -p '#S-#I-#P')"
fi

# Disable = command
unsetopt EQUALS

# Disable r command
disable r

# Set editor
if [[ -z "$EDITOR" ]]; then
  command -v vim >/dev/null 2>&1 && export EDITOR=vim
  command -v nvim >/dev/null 2>&1 && export EDITOR=nvim
fi

#Locale
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

# Add v command on normal mode to edit current line with $EDITOR
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

export LD_LIBRARY_PATH=/usr/local/lib

# Load personal configs
. ~/.dotfiles/zsh/path.zsh
. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/functions.zsh
. ~/.dotfiles/zsh/completion.zsh
. ~/.dotfiles/zsh/bind.zsh
. ~/.dotfiles/zsh/fzf.zsh
. ~/.dotfiles/git/git-aliases.zsh
. ~/.dotfiles/zsh/plugins.zsh

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
